/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export type TSWrapper = TsWrapper
export class TsWrapper {
  constructor(text: string)
  getText(): string
}
